name: CD Pipeline

on:
  push:
    branches:
      - main  # main 브랜치에 push 되었을 때 실행

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    env:
      EC2_HOST: ${{ secrets.EC2_HOST }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      IMAGE_TAG: ${{ github.sha }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_REPOSITORY: ${{ secrets.DOCKER_REPOSITORY }}

    steps:
      # 깃헙 리포지토리 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4

      # gradlew 실행 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # JDK 설정
      - name: Set up and JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      # .jar 빌드
      - name: Build jar
        run: ./gradlew --info clean bootJar -x test

      # docker 로그인
      - name: docker login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Print Docker envs
        run: |
          echo "DOCKER_USERNAME=${{ env.DOCKER_USERNAME }}"
          echo "DOCKER_REPOSITORY=${{ env.DOCKER_REPOSITORY }}"
          echo "IMAGE_TAG=${{ env.IMAGE_TAG }}"

      # image build 및 push
      - name: docker build and push
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          push: true
          cache-from: type=registry,ref=${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_REPOSITORY }}:${{ env.IMAGE_TAG }}
          cache-to: type=inline
          tags: ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_REPOSITORY }}:${{ env.IMAGE_TAG }}

      # EC2 연결 및 쉘 스크립트 실행
      - name: Deploy to EC2 (main branch)
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@master
        env:
          ENV_FILE: "/home/ubuntu/.env"
        with:
          host: ${{ env.EC2_HOST }}
          username: ubuntu
          key: ${{ env.SSH_KEY }}
          script: |
            echo "Starting deployment with image tag: $IMAGE_TAG"
            ./deploy.sh $IMAGE_TAG